# Generated by Django 3.2 on 2021-11-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0002_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
