# Generated by Django 3.2 on 2021-11-09 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0004_degree_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='degr',
            field=models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, related_name='display', to='datacard.degree'),
        ),
    ]
