# Generated by Django 3.2 on 2021-11-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0005_alter_exam_degr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='degr',
        ),
        migrations.AddField(
            model_name='exam',
            name='deg',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam',
            field=models.ManyToManyField(default='', editable=False, to='datacard.Degree'),
        ),
    ]
