# Generated by Django 3.2 on 2021-11-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0006_auto_20211110_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='deg',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam',
        ),
        migrations.AddField(
            model_name='degree',
            name='exm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exam',
            name='exm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.RemoveField(
            model_name='degree',
            name='deg',
        ),
        migrations.AddField(
            model_name='degree',
            name='deg',
            field=models.ManyToManyField(to='datacard.Exam'),
        ),
    ]
