# Generated by Django 3.2 on 2021-11-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0009_auto_20211110_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exm',
        ),
        migrations.AddField(
            model_name='degree',
            name='exm',
            field=models.ManyToManyField(to='datacard.Exam'),
        ),
    ]
