# Generated by Django 3.2 on 2021-11-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0010_auto_20211110_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='exm',
        ),
        migrations.AddField(
            model_name='exam',
            name='exm',
            field=models.ManyToManyField(to='datacard.Degree'),
        ),
    ]
