# Generated by Django 3.2 on 2021-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0011_auto_20211111_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='deg',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exm',
        ),
        migrations.AddField(
            model_name='degree',
            name='exm',
            field=models.ManyToManyField(to='datacard.Exam'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam',
            field=models.CharField(default='', max_length=200),
        ),
    ]
