# Generated by Django 3.2 on 2021-11-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0012_auto_20211111_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam',
            new_name='exm',
        ),
    ]
