# Generated by Django 3.2 on 2021-11-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0013_rename_exam_exam_exm'),
    ]

    operations = [
        migrations.CreateModel(
            name='t1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exm', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='t2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deg', models.CharField(default='', max_length=200)),
                ('exm', models.ManyToManyField(to='datacard.t1')),
            ],
        ),
    ]
