# Generated by Django 3.2 on 2021-11-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0014_t1_t2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t2',
            name='exm',
        ),
        migrations.DeleteModel(
            name='t1',
        ),
        migrations.DeleteModel(
            name='t2',
        ),
    ]
