# Generated by Django 3.2 on 2021-12-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0016_appeared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadpdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certs', models.FileField(blank=True, null=True, upload_to='certs/')),
            ],
        ),
    ]
