# Generated by Django 3.2 on 2021-12-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0017_uploadpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadpdf',
            name='nam',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
