# Generated by Django 3.2 on 2021-12-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0019_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
        migrations.DeleteModel(
            name='Web',
        ),
    ]
