# Generated by Django 3.2 on 2021-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0020_auto_20211208_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='use',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
