# Generated by Django 3.2 on 2021-12-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0021_photo_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='use',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
