# Generated by Django 3.2 on 2021-12-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacard', '0022_detail_use'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploadpdf',
        ),
    ]
